version: "3.9"
services:
  backend-api:
    # image: "backend-image"
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Development
    ports:
      - "5000:80"
  frontend:
    # image: "frontend-image"
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Development
    ports:
      - "8080:80"
    depends_on:
      - backend-api